package(
    default_visibility = ["//rhutil:internal"],
    default_testonly = 1,
)

cc_library(
    name = "assertions",
    hdrs = ["assertions.h"],
    srcs = ["assertions.cc"],
    deps = [
        "//rhutil:status",
        "@googletest//:gtest"
    ],
    visibility = ["//visibility:public"],
)
